[package]
name = "lambdaman"
version = "0.1.0"
edition = "2021"

[dependencies]
ac-library-rs = "0.1.1"
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
itertools = "0.13.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
rayon = "1.10.0"
